1) MEMBER_NAME CHAR(30) 구문
MEMBER_NAME 컬럼에 가변 길이 문자열로 설정하길 요구했으나 CHAR 자료형을 사용해 고정 길이 문자열로 작성

2) BOARD_REG_DATE DATE DEFAULT '2023-03-22' 구문
BOARD_REG_DATE(작성일) 컬럼에 현재 시간으로 기본값 설정을 요구하였으나 현재 시간을 의미하는 CURRENT_DATE를 작성해주지 않음

3) BOARD_WRITER VARCHAR2(20) FOREIGN KEY MEMBERS(MEMBER_ID) 구문
BOARD_WRITER 컬럼에 MEMERS 테이블의 MEMBER_ID를 참조하는 FOREIGN KEY 제약조건 설정하길 요구했으나 참조(REFERENCES)할 테이블명과 컬럼명을 작성하지 않아 오류가 발생

1) 가변 길이 문자열 자료형을 설정하기 위해
MEMBER_NAME CHAR(30) 구문을 

MEMBER_NAME VARCHAR2(30) 로 변경

2) 현재 시간으로 기본값 설정하기 위해 
BOARD_REG_DATE DATE DEFAULT '2023-03-22' 구문을 

BOARD_REG_DATE DATE DEFAULT CURRENT_DATE 로 변경

3) 참조할 테이블과 컬럼명을 작성하고 테이블 레벨 설정으로 작성하기 위해 
BOARD_WRITER VARCHAR2(20) FOREIGN KEY MEMBERS(MEMBER_ID) 구문을 

BOARD_WRITER VARCHAR2(20)
,CONSTRAINT BOARD_WRITER_FK 
FOREIGN KEY (BOARD_WRITER) 
REFERENCES MEMBERS(MEMBER_ID) 로 변경

/* - MEMBERS 테이블 
1) MEMBER_ID 컬럼에 PRIMARY KEY 제약조건 설정.
2) MEMBER_PWD 컬럼에 NOT NULL 제약조건 설정.
3) MEMBER_NAME 컬럼에 가변 길이 문자열 30byte 설정.

 - BOARDS 테이블 
1) BOARD_NO 컬럼에 PRIMARY KEY 제약조건 설정.
2) BOARD_WRITER 컬럼에 MEMERS 테이블의 MEMBER_ID를 참조하는 FOREIGN KEY 제약조건 설정.
3) BOARD_REG_DATE(작성일) 컬럼에 현재 시간으로 기본값 설정   */

-- [작성한 SQL문]

-- MEMBERS 테이블 생성

CREATE TABLE MEMBERS(
MEMBER_ID VARCHAR2(20),
MEMBER_PWD VARCHAR2(20) NOT NULL,
MEMBER_NAME VARCHAR2(30),
MEMBER_AGE NUMBER,
MEMBER_EMAIL VARCHAR2(50),
PRIMARY KEY(MEMBER_ID)
);
DELETE
FROM MEMBERS;
INSERT INTO MEMBERS VALUES (1, 1, 'A', 1, 1);
INSERT INTO MEMBERS VALUES (2, 2, 'B', 2, 2);
INSERT INTO MEMBERS VALUES (3, 3, 'C', 3, 3);

SELECT * FROM MEMBERS;

-- BOARDS 테이블 생성
CREATE TABLE BOARDS(
BOARD_NO NUMBER PRIMARY KEY,
BOARD_TITLE VARCHAR2(100),
BOARD_CONTENT VARCHAR2(4000),
BOARD_WRITER VARCHAR2(20),
BOARD_REG_DATE DATE DEFAULT CURRENT_DATE

,CONSTRAINT BOARD_WRITER_FK 
FOREIGN KEY (BOARD_WRITER) 
REFERENCES MEMBERS(MEMBER_ID)
);




