-- 1. 서브쿼리 내 WHERE절 컬럼명을 AREA_CODE로 작성했으나 TB_MEMBER 테이블에 해당 컬럼이 존재하지 않아 오류가 발생
--> 요구사항에 맞게 MEMBER_NAME 컬럼으로 변경

-- 2. 후순위로 읽어지는 메인쿼리 SELECT절에 선언한 별칭(이름)을 서브쿼리에 사용하여 오류가 발생
--> WHERE절 WHERE 이름 = '김영희'; 를 WHERE MEMBER_NAME = '김영희';로 변경

-- 3. 2번째 JOIN절 JOIN TB_AREA ON (AREA_CODE = AREA_CODE) 어느 테이블의 AREA_CODE인지 구분해주지 않아 오류가 발생
--> TB_MEMBER 테이블과 TB_AREA 테이블에 별칭을 선언해준 뒤 각 AREA_CODE를 구분해주어야 함

-- 4. 요구사항은 오름차순 조회이나 내림차순으로 조회됨
--> DESC ASC로 변경



/*SELECT AREA_NAME 지역명, MEMBER_ID 아이디, MEMBER_NAME 이름, GRADE_NAME 등급명
FROM TB_MEMBER
JOIN TB_GRADE ON(GRADE = GRADE_CODE)
JOIN TB_AREA ON (AREA_CODE = AREA_CODE)
WHERE AREA_CODE = (
SELECT AREA_CODE FROM TB_MEMBER
WHERE 이름 = '김영희')
ORDER BY 이름 DESC;*/ 

SELECT A.AREA_NAME 지역명, M.MEMBER_ID 아이디, M.MEMBER_NAME 이름, GRADE_NAME 등급명
FROM TB_MEMBER M
JOIN TB_GRADE ON(M.GRADE = GRADE_CODE)
JOIN TB_AREA A ON(M.AREA_CODE = A.AREA_CODE)
WHERE M.AREA_CODE = (
SELECT AREA_CODE FROM TB_MEMBER
WHERE MEMBER_NAME = '김영희')
ORDER BY 이름 ASC;



/*(SELECT AREA_NAME
FROM TB_MEMBER
WHERE MEMBER_NAME = '김영희')*/

/*SELECT AREA_NAME 지역명, MEMBER_ID 아이디, MEMBER_NAME 이름, GRADE_NAME 등급명
FROM TB_MEMBER M 
JOIN TB_GRADE ON(GRADE_CODE = GRADE)
JOIN TB_AREA A ON (M.AREA_CODE = A.AREA_CODE)
WHERE MEMBER_NAME = '김영희';*/ 

/*SELECT AREA_NAME 지역명, MEMBER_ID 아이디, MEMBER_NAME 이름, GRADE_NAME 등급명
FROM TB_MEMBER M
JOIN TB_GRADE ON(GRADE = GRADE_CODE)
JOIN TB_AREA A ON(M.AREA_CODE = A.AREA_CODE)
GROUP BY AREA_CODE;*/
SELECT AREA_NAME 지역명, MEMBER_ID 아이디, MEMBER_NAME 이름, GRADE_NAME 등급명
FROM TB_MEMBER M
JOIN TB_GRADE ON(GRADE_CODE = GRADE)
JOIN TB_AREA A ON (M.AREA_CODE = A.AREA_CODE)
HAVING AERA_CODE = (
SELECT AERA_CODE
FROM TB_MEMBER
WHERE MEMBER_NAME = '김영희')

ORDER BY 이름 ASC;






